### ISSUE TITLE
Missing "--" before "config=" in run.sh?

### ISSUE THREAD

**Issue by bendikp** [fabric8io/docker-grafana#1]
I did not manage to get custom config to work when mounting my custom config to /etc/grafana/grafana.ini. But when i mounted my custom config to /usr/share/grafana/conf/custom.ini it worked.

There seems to be missing "--" before "config=" in run.sh.
https://github.com/fabric8io/docker-grafana/blob/master/run.sh#L25

**Comment by davsclaus** [comment]
Ah thanks for spotting. Do you want to do a PR to fix this?
